package redhat.cloudapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApprovalRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String userTag;
   private java.lang.String serviceTag;
   private java.lang.String productTag;
   private java.lang.String requester;
   private java.lang.String serviceName;

   private java.util.List<redhat.cloudapproval.Approver> approver;

   private java.lang.String approvalRequired;

   private java.lang.String approvalStatus;

   private long pid;

   public ApprovalRequest()
   {
   }

   public java.lang.String getUserTag()
   {
      return this.userTag;
   }

   public void setUserTag(java.lang.String userTag)
   {
      this.userTag = userTag;
   }

   public java.lang.String getServiceTag()
   {
      return this.serviceTag;
   }

   public void setServiceTag(java.lang.String serviceTag)
   {
      this.serviceTag = serviceTag;
   }

   public java.lang.String getProductTag()
   {
      return this.productTag;
   }

   public void setProductTag(java.lang.String productTag)
   {
      this.productTag = productTag;
   }

   public java.lang.String getRequester()
   {
      return this.requester;
   }

   public void setRequester(java.lang.String requester)
   {
      this.requester = requester;
   }

   public java.lang.String getServiceName()
   {
      return this.serviceName;
   }

   public void setServiceName(java.lang.String serviceName)
   {
      this.serviceName = serviceName;
   }

   public java.util.List<redhat.cloudapproval.Approver> getApprover()
   {
      return this.approver;
   }

   public void setApprover(java.util.List<redhat.cloudapproval.Approver> approver)
   {
      this.approver = approver;
   }

   public java.lang.String getApprovalRequired()
   {
      return this.approvalRequired;
   }

   public void setApprovalRequired(java.lang.String approvalRequired)
   {
      this.approvalRequired = approvalRequired;
   }

   public java.lang.String getApprovalStatus()
   {
      return this.approvalStatus;
   }

   public void setApprovalStatus(java.lang.String approvalStatus)
   {
      this.approvalStatus = approvalStatus;
   }

   public long getPid()
   {
      return this.pid;
   }

   public void setPid(long pid)
   {
      this.pid = pid;
   }

   public ApprovalRequest(java.lang.String userTag, java.lang.String serviceTag,
         java.lang.String productTag, java.lang.String requester,
         java.lang.String serviceName,
         java.util.List<redhat.cloudapproval.Approver> approver,
         java.lang.String approvalRequired, java.lang.String approvalStatus,
         long pid)
   {
      this.userTag = userTag;
      this.serviceTag = serviceTag;
      this.productTag = productTag;
      this.requester = requester;
      this.serviceName = serviceName;
      this.approver = approver;
      this.approvalRequired = approvalRequired;
      this.approvalStatus = approvalStatus;
      this.pid = pid;
   }

}