package redhat.cloudapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String type;

   public Approver()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public Approver(java.lang.String name, java.lang.String type)
   {
      this.name = name;
      this.type = type;
   }

}